<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="115" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="115" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
      <class name="testCases.TC_1">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testCases.TC_1@1786dec2]" name="beforeSuite" is-config="true" duration-ms="455" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testCases.TC_1@1786dec2]" name="beforeTest" is-config="true" duration-ms="3" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testCases.TC_1@1786dec2]" name="setData" is-config="true" duration-ms="1" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="FAIL" signature="loginApp()[pri:0, instance:testCases.TC_1@1786dec2]" name="loginApp" duration-ms="0" started-at="2020-04-29T16:21:37Z" data-provider="fetchData" finished-at="2020-04-29T16:21:37Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.lang.Object[][] reusables.CustomsListener.getData() returned a null value]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] reusables.CustomsListener.getData() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testCases.TC_1@1786dec2]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testCases.TC_1@1786dec2]" name="afterSuite" is-config="true" duration-ms="1" started-at="2020-04-29T16:21:37Z" finished-at="2020-04-29T16:21:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testCases.TC_1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
